import os

DATABASE_URL = os.getenv("DATABASE_URL")

APP_SECRET = os.getenv("APP_SECRET", "change-me")

# --- M-Pesa Daraja ---
MPESA_CONSUMER_KEY = os.getenv("MPESA_CONSUMER_KEY")
MPESA_CONSUMER_SECRET = os.getenv("MPESA_CONSUMER_SECRET")
MPESA_SHORTCODE = os.getenv("MPESA_SHORTCODE")
MPESA_PASSKEY = os.getenv("MPESA_PASSKEY")
MPESA_CALLBACK_URL = os.getenv("MPESA_CALLBACK_URL")

# --- WAMD (Kuwait) ---
WAMD_API_KEY = os.getenv("WAMD_API_KEY")
WAMD_CALLBACK_URL = os.getenv("WAMD_CALLBACK_URL")
